### ISSUE TITLE
ModuleGrading not working properly

### ISSUE THREAD

**Issue by Chris-Howkins** [JCanning1/com2008-info-system#61]
The getGradeGroup method seems to not be working properly, I'm not quite sure why, the error seems to be on line 86: java.sql.SQLException: Column 'students.forename ' not found. 
If you look in the CreateGradingUI, that contains the most up to date ModuleGrading class as I had to change a few things to get it working with the add grades UI. Also, I'm not sure how the user should select the start date as that is one of the things that the prepared statement needs in that method. If you could have a look at this, that would be great @tomsnowgb

**Comment by tomsnowgb** [comment]
Will sort 😱

**Comment by Chris-Howkins** [comment]
Alright cool, thanks
